audio/libmpd: unbreak build with LLVM15 (+)
Pass -Wno-int-conversion to CFLAGS fixes error with strict conversion rules introduced in LLVM15

libmpd-playlist.c:783:10: error: incompatible pointer to integer conversion returning 'void *' from a function with result type 'int' [-Wint-conversion]
                return NULL;
                       ^~~~
/usr/include/sys/_null.h:34:14: note: expanded from macro 'NULL'
                ^~~~~~~~~~~

Sponsored by:   Serenity Cybersecurity, LLC