devel/collada-dom: unbreak build with LLVM15 (+)
Pass -Wno-int-conversion to CFLAGS fixes error with strict conversion rules introduced in LLVM15

/wrkdirs/usr/ports/devel/collada-dom/work/collada-dom-2.5.0/dom/external-libs/minizip-1.1/ioapi.c:115:14: error: incompatible integer to pointer conversion assigning to 'FILE *' (aka 'struct __sFILE *')
 from 'int' [-Wint-conversion]
        file = fopen64((const char*)filename, mode_fopen);
             ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~